version: '3.9'
services:
  certmon-server:
    container_name: certmon-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80